"""Phase 11: Add quiz attempts and answers

Revision ID: 3e2d5d1ea7d1
Revises: h8i9j0k1l2m3
Create Date: 2026-03-21 23:47:37.597318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e2d5d1ea7d1'
down_revision = 'h8i9j0k1l2m3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('quiz_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('score_percentage', sa.Float(), nullable=True),
    sa.Column('points_awarded', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_attempts_quiz_id'), 'quiz_attempts', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_user_id'), 'quiz_attempts', ['user_id'], unique=False)
    op.create_table('quiz_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('selected_option_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['quiz_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_answers_attempt_id'), 'quiz_answers', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_quiz_answers_question_id'), 'quiz_answers', ['question_id'], unique=False)
    op.alter_column('courses', 'visibility',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('everyone', 'signed_in', name='coursevisibility', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'everyone'::character varying"))
    op.alter_column('courses', 'access_rule',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('open', 'on_invitation', 'on_payment', name='courseaccessrule', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'open'::character varying"))
    op.alter_column('enrollments', 'status',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('enrolled', 'in_progress', 'completed', name='enrollmentstatus', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'enrolled'::character varying"))
    op.alter_column('lesson_attachments', 'type',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('file', 'link', name='attachmenttype', native_enum=False),
               existing_nullable=False)
    op.alter_column('lessons', 'type',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('video', 'document', 'image', name='lessontype', native_enum=False),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('admin', 'instructor', 'learner', name='userrole', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('admin', 'instructor', 'learner', name='userrole', native_enum=False),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('lessons', 'type',
               existing_type=sa.Enum('video', 'document', 'image', name='lessontype', native_enum=False),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('lesson_attachments', 'type',
               existing_type=sa.Enum('file', 'link', name='attachmenttype', native_enum=False),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('enrollments', 'status',
               existing_type=sa.Enum('enrolled', 'in_progress', 'completed', name='enrollmentstatus', native_enum=False),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'enrolled'::character varying"))
    op.alter_column('courses', 'access_rule',
               existing_type=sa.Enum('open', 'on_invitation', 'on_payment', name='courseaccessrule', native_enum=False),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'open'::character varying"))
    op.alter_column('courses', 'visibility',
               existing_type=sa.Enum('everyone', 'signed_in', name='coursevisibility', native_enum=False),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'everyone'::character varying"))
    op.drop_index(op.f('ix_quiz_answers_question_id'), table_name='quiz_answers')
    op.drop_index(op.f('ix_quiz_answers_attempt_id'), table_name='quiz_answers')
    op.drop_table('quiz_answers')
    op.drop_index(op.f('ix_quiz_attempts_user_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_quiz_id'), table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    # ### end Alembic commands ###
