"""Add quiz_id to Lesson model

Revision ID: 5b0cf956603a
Revises: 3e2d5d1ea7d1
Create Date: 2026-03-21 23:51:42.896817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b0cf956603a'
down_revision = '3e2d5d1ea7d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('quiz_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'lessons', 'quizzes', ['quiz_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.drop_column('lessons', 'quiz_id')
    # ### end Alembic commands ###
